name: nb_utils
description: "Collection of Widgets and helpful Methods that every developer needs."
version: 7.0.8
#homepage: https://bhoominn.github.io
repository: https://github.com/bhoominn/nb_utils
issue_tracker: https://github.com/bhoominn/nb_utils/issues
funding:
  - https://www.github.com/sponsors/bhoominn

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  plugin_platform_interface: ^2.1.8

  shared_preferences: ^2.3.4
  fluttertoast: ^8.2.10
  connectivity_plus: ^6.1.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.nb_utils
        pluginClass: NbUtilsPlugin
      ios:
        pluginClass: NbUtilsPlugin
      linux:
        pluginClass: NbUtilsPlugin
      macos:
        pluginClass: NbUtilsPlugin
      windows:
        pluginClass: NbUtilsPluginCApi
      web:
        pluginClass: NbUtilsWeb
        fileName: nb_utils_web.dart

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: fonts/LineAwesome.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/icons/

topics:
  - widgets
  - extensions
  - utils
  - chatgpt
  - flutterutils
